### ISSUE TITLE
'TiffPageType' is not a constant, variable or function identifier

### ISSUE THREAD

**Issue by Fromandto** [facebookresearch/sumo-challenge#12]
When executing 'python setup.py build_ext --inplace'
I am using Python 3.5.2 on Ubuntu 16.04

```
Error compiling Cython file:
------------------------------------------------------------
...
      page_map[TiffPageType.InverseDepth] = <Mat*>mat1w_from_array(inv_depth)
    elif page_type == MultiImagePageType.InverseDepth:
      # Here we use MultiImagePageType.Depth because the underlying cpp code
      # is already expecting inverse depth for this key, while the input to
      # this function does not
      page_map[TiffPageType.InverseDepth] = <Mat*>mat1w_from_array(img_np)
                          ^
------------------------------------------------------------

sumo/images/rgbd_tiff.pyx:146:27: 'TiffPageType' is not a constant, variable or function identifier
```

**Comment by NCBee** [comment]
Looking into it. To me it's a cython compiler bug. Do you know the cython version you are using?

**Comment by NCBee** [comment]
@dhuber23b Could this be the issue? https://github.com/cython/cython/issues/1529

**Comment by dhuber23b** [comment]
I am not seeing this problem with Cython version 0.27.3.  Please tell us your version of Cython.

**Comment by Fromandto** [comment]
I set up the virtual environment as guided, and I find my Cython version is 0.23.4. I will try to upgrade it to 0.27.3

**Comment by Fromandto** [comment]
Now everything is fine and all unit tests passed. I'll close the issue.
