### ISSUE TITLE
rgbdci_360.pyx

### ISSUE THREAD

**Issue by Fromandto** [facebookresearch/sumo-challenge#13]
https://github.com/facebookresearch/sumo-challenge/blob/master/sumo-api/sumo/images/rgbdci_360.pyx

It seems that in line 126, same_size() is not implemented and in line 129 the input should be self.range ?

**Comment by NCBee** [comment]
@dhuber23b Are we missing range to depth conversion or we are now calling references to depth 'range'?

**Comment by dhuber23b** [comment]
This is a copy-paste error from some internal code.  I am working on fixing it now.  We should also add a test for point cloud generation.

**Comment by dhuber23b** [comment]
Fixed.
