### ISSUE TITLE
ask for Getting Started / Quick Examples page

### ISSUE THREAD

**Issue by amiltonwong** [facebookresearch/sumo-challenge#59]
Hi, all,

Would you provide a Getting Started / Quick Examples page for the challenge. The [white paper](https://github.com/facebookresearch/sumo-challenge/blob/master/docs/assets/sumo-white-paper.pdf) only gives the specification on the related data structure and evaluation error, it doesn't help much for some one to start the challenge. 
Moreover, would you also list some published papers related to sumo-challenge? As it was held last year, some previous works may already be published.

THX!

**Comment by dhuber23b** [comment]
The web site has been updated with a link to the SUMO API documentation web site, which is https://facebookresearch.github.io/sumo-challenge/  Additional details will be added to this site as time permits.  We are also working on some starter code that integrates with PyTorch.

**Comment by dhuber23b** [comment]
We are also working on a summary paper to provide an overview of the challenge from the fall.

**Comment by amiltonwong** [comment]
Thanks a lot @dhuber23b  :)
