### ISSUE TITLE
from sumo.images.rgbdci_360 import Rgbdci360

### ISSUE THREAD

**Issue by DapengFeng** [facebookresearch/sumo-challenge#68]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sumo/threedee/point_cloud.pxd", line 31, in init sumo.images.rgbdci_360
ImportError: /home/right/anaconda3/lib/python3.7/site-packages/sumo-1.0-py3.7-linux-x86_64.egg/sumo/threedee/point_cloud.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

**Comment by nydragon** [comment]
It seems a problem of opencv. I recompile opencv from source and it works.
